import { Tour } from 'nextstepjs/dist/types';

const steps : Tour[] = [
        {
            tour: "mainTour",
            steps: [
                {
                    icon: null,
                    title: "Welcome to Oryna AI!",
                    content: "This tour will guide you through the main features of the dashboard.",
                    selector: "#navigation-bar",
                    side: "bottom",
                    showControls: true,
                    showSkip: true,
                },
                {
                    icon: null,
                    title: "Saved Gallery",
                    content: "Here you can view and manage your saved virtual try-on images.",
                    selector: "#saved-gallery",
                    side: "right",
                    showControls: true,
                    showSkip: true,
                },
                {
                    icon: null,
                    title: "Generation Section",
                    content: "Use this section to upload images and generate virtual try-ons.",
                    selector: "#generation-section",
                    side: "left",
                    showControls: true,
                    showSkip: true,
                },
                {
                    icon: null,
                    title: "Coin System",
                    content: "You can earn and spend coins for generating virtual try-ons.",
                    selector: "#coin-display",
                    side: "bottom",
                    showControls: true,
                    showSkip: true,
                },
                {
                    icon: null,
                    title: "upload your images",
                    content: "Click here to upload your images for virtual try-on.",
                    selector: "#upload-button-person",
                    side: "top",
                    showControls: true,
                    showSkip: true, 
                },
                {
                    icon: null,
                    title: "upload the clothing image",
                    content: "Click here to upload the clothing image for virtual try-on.",
                    selector: "#upload-button-clothing",
                    side: "top",
                    showControls: true,
                    showSkip: true, 
                },
                {
                    icon: null,
                    title: "Generate Virtual Try-On",
                    content: "After uploading images, click here to generate the virtual try-on.",
                    selector: "#generate-button",
                    side: "top",
                    showControls: true,
                    showSkip: true,
                },
                {
                    icon: null,
                    title: "End of Tour",
                    content: "This concludes the tour. Enjoy using Oryna AI!",
                    selector: "#navigation-bar",
                    side: "bottom",
                    showControls: true,
                    showSkip: false,
                },
            ],
        },
];
export default steps;